name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      project_ref:
        description: "Supabase project ref (overrides FN)"
        required: false
      functions_url:
        description: "Full functions base URL (if not standard)"
        required: false

jobs:
  at:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # You can store SERVICE_ROLE and URL in repo or org secrets; service role is sensitive.
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      CLIENT_ID: 1b387371-6711-485c-81f7-79b2174b90fb
      GUARD_ID: c38efbac-fd1e-426b-a0ab-be59fd908c8c
      CITY: CDMX
      TIER: direct
      HOURS: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive Functions URL
        id: fnurl
        run: |
          if [ -n "${{ github.event.inputs.functions_url }}" ]; then
            echo "FN=${{ github.event.inputs.functions_url }}" >> $GITHUB_ENV
          elif [ -n "${{ github.event.inputs.project_ref }}" ]; then
            echo "FN=https://${{ github.event.inputs.project_ref }}.supabase.co/functions/v1" >> $GITHUB_ENV
          elif [ -n "$SUPABASE_URL" ]; then
            # SUPABASE_URL is like https://<ref>.supabase.co
            echo "FN=${SUPABASE_URL%/}/functions/v1" >> $GITHUB_ENV
          else
            echo "::error::Unable to derive FN (provide project_ref or functions_url or SUPABASE_URL secret)"; exit 1;
          fi
          echo "Using FN=$FN"

      - name: Install jq & curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Show FN
        run: echo "FN=$FN"

      - name: Run Acceptance Tests
        run: |
          chmod +x scripts/at.sh
          ./scripts/at.sh

      - name: Summary
        if: always()
        run: |
          echo "Workflow complete."
