name: Post-deploy smoke (optional)

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Hit /health endpoint
        run: |
          set -euo pipefail
          : "${HEALTH_URL?Set HEALTH_URL (e.g., https://<project>.functions.supabase.co/health)}"
          code=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL")
          test "$code" = "200" || (echo "Health check failed: $code" && exit 1)
