name: Smoke
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/**'
      - 'scripts/smoke.sh'
      - 'public/**'
  schedule:
    - cron: '17 3 * * *' # daily 03:17 UTC

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.SUPABASE_ANON_KEY }}" ]; then
            echo "Missing repository secret SUPABASE_ANON_KEY."
            echo "Add it in GitHub → Settings → Secrets and variables → Actions."
            exit 1
          fi
      - name: Install jq & curl
        run: sudo apt-get update && sudo apt-get install -y jq curl
      - name: Run smoke
        env:
          FN: https://isnezquuwepqcjkaupjh.supabase.co/functions/v1
          CLIENT_ID: 1b387371-6711-485c-81f7-79b2174b90fb
          GUARD_ID: c38efbac-fd1e-426b-a0ab-be59fd908c8c
          ANON: ${{ secrets.SUPABASE_ANON_KEY }}
        run: bash scripts/smoke.sh
